$(document).ready(function(){
	var FieldCount=1; //to keep track of text box added
	FieldCount++;
	$("#dd").click(function(){
		$("#dd").toggleClass('active');
	});
	$('#generalinfo').click(function()
	{
		$('#information').css('display','block');
		$('#document').css('display','none');
		$('#video').css('display','none');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").addClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#docu').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','block');
		$('#video').css('display','none');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").addClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#videosec').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','block');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").addClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#videosec').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','block');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").addClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#visionsec').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','none');
		$('#vision').css('display','block');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").addClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#products').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','none');
		$('#vision').css('display','none');
		$('#pro').css('display','block');
		$('#serv').css('display','none');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").addClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#services').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','none');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','block');
		$('#cont').css('display','none');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").addClass("user_active");
		$("#contact").removeClass("user_active");
	});
	$('#contact').click(function()
	{
		$('#information').css('display','none');
		$('#document').css('display','none');
		$('#video').css('display','none');
		$('#vision').css('display','none');
		$('#pro').css('display','none');
		$('#serv').css('display','none');
		$('#cont').css('display','block');
		$("#generalinfo").removeClass("user_active");
		$("#docu").removeClass("user_active");
		$("#videosec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#products").removeClass("user_active");
		$("#services").removeClass("user_active");
		$("#contact").addClass("user_active");
	});
	
	$('#skip1').click(function()
	{
		$('#information').css('display','none');
		$('#video_section').css('display','block');
		$("#generalinfo").removeClass	("user_active");
		$("#videosec").addClass("user_active");
		$("#resourcessec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#productsser").removeClass("user_active");
		$("#companycont").removeClass("user_active");
	});
	$('#skip2').click(function()
	{
		$('#video_section').css('display','none');
		$('#resource_section').css('display','block');
		$("#generalinfo").removeClass	("user_active");
		$("#videosec").removeClass("user_active");
		$("#resourcessec").addClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#productsser").removeClass("user_active");
		$("#companycont").removeClass("user_active");
	});
	$('#skip3').click(function()
	{
		$('#resource_section').css('display','none');
		$('#vstatement').css('display','block');
		$("#generalinfo").removeClass	("user_active");
		$("#videosec").removeClass("user_active");
		$("#resourcessec").removeClass("user_active");
		$("#visionsec").addClass("user_active");
		$("#productsser").removeClass("user_active");
		$("#companycont").removeClass("user_active");
	});
	$('#skip4').click(function()
	{
		$('#vstatement').css('display','none');
		$('#pro_serv').css('display','block');
		$("#generalinfo").removeClass	("user_active");
		$("#videosec").removeClass("user_active");
		$("#resourcessec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#productsser").addClass("user_active");
		$("#companycont").removeClass("user_active");
	});
	$('#skip5').click(function()
	{
		$('#pro_serv').css('display','none');
		$('#com_cont').css('display','block');
		$('#vstatement').css('display','none');
		$('#pro_serv').css('display','none');
		$("#generalinfo").removeClass	("user_active");
		$("#videosec").removeClass("user_active");
		$("#resourcessec").removeClass("user_active");
		$("#visionsec").removeClass("user_active");
		$("#productsser").removeClass("user_active");
		$("#companycont").addClass("user_active");
	});
	$('input[id=cmpny_img]').attr(
					'accept',
					'image/*'
				);
	$('input[id=docfile]').attr(
					'accept',
					'text/*,.docx,.pdf,.xlsx'
				);
		
	$('input[id=docfile]').change(function()
	{
  	  $('#photoCover').val($(this).val());
    });
	
	$('input[id=vidfile]').attr(
					'accept',
					'video/*'
				);
	$('input[id=vidfile]').change(function()
	{
  	  $('#photoCover3').val($(this).val());
    });

});

	