INSERT IGNORE INTO ORIGO_MST_PARTNERSHIP_TYPES VALUES (1, 'Business partnership ');
INSERT IGNORE INTO ORIGO_MST_PARTNERSHIP_TYPES VALUES (2, 'Product partnership');
INSERT IGNORE INTO ORIGO_MST_PARTNERSHIP_TYPES VALUES (3, 'Joint Ventures ');
INSERT IGNORE INTO ORIGO_MST_PARTNERSHIP_TYPES VALUES (4, 'Media partnership');
INSERT IGNORE INTO ORIGO_MST_PARTNERSHIP_TYPES VALUES (5, 'Strategic Alliances');


INSERT IGNORE INTO ORIGO_MST_CERTIFICATION_TYPES VALUES (1, 'ISO-9000');
INSERT IGNORE INTO ORIGO_MST_CERTIFICATION_TYPES VALUES (2, 'ISO-9001');


